### ISSUE TITLE
Validation guide not working

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/windowsserverdocs.pt-br#2]
The link for validation guide is not working. Please, could you fix it?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 7db91f6a-373f-70d5-7e5e-455e08a1d9e1
* Version Independent ID: 2f44b38f-dadd-689b-c90e-2d2ea2c93528
* Content: [Recursos do serviço de tempo do insider Preview para Windows no Windows Server 2019](https://docs.microsoft.com/pt-br/windows-server/networking/windows-time-service/insider-preview)
* Content Source: [WindowsServerDocs/networking/windows-time-service/insider-preview.md](https://github.com/MicrosoftDocs/windowsserverdocs.pt-br/blob/live/WindowsServerDocs/networking/windows-time-service/insider-preview.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by srvbpigh** [comment]
Hello, @ingd
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ingd

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windowsserverdocs/issues/3476

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
